changelog:
  categories:
    - title: Added
      labels:
        - 'Type: Add'
    - title: Changed
      labels:
        - 'Type: Change'
    - title: Deprecated
      labels:
        - 'Type: Deprecate'
    - title: Fixed
      labels:
        - 'Type: Fix'
    - title: Removed
      labels:
        - 'Type: Remove'
    - title: Security
      labels:
        - 'Type: Security'
    - title: Others
      labels:
        - "*"
